version: '3.8'

services:
  minecraft-forge:
    # 告诉 Docker Compose 使用当前目录的 Dockerfile 来构建镜像
    build:
      context: .
      dockerfile: dockerfile
      args:
        - JAVA_VERSION=17
        - MC_VERSION=1.18.2
        - FORGE_VERSION=40.2.4
        - PACK_NAME=packs
    # 为构建出的镜像指定一个明确的名称和标签
    image: my-forge-server:1.18.2-forge-40.2.4
    
    container_name: minecraft-forge-server
    
    environment:
      - EULA=TRUE
      - MC_VERSION=1.18.2
      - FORGE_VERSION=40.2.4
    
    ports:
      - "25565:25565"  # Minecraft 服务器端口
    
    volumes:
      # 挂载世界存档和配置文件到主机，实现数据持久化
      - ./data/world:/app/world
      - ./data/modified_data:/app/modified_data
  
      
    restart: unless-stopped
    
    # 设置内存限制
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 2G
