version: '3.8'

services:
  minecraft-forge:
    # 使用预构建的镜像
    image: "crpi-vv1v4s4fdwh8q4xq.cn-hangzhou.personal.cr.aliyuncs.com/autsch/forge-mc-server:Planetary-1.0.0-alpha"
    
    container_name: planetary-server
    
    environment:
      - EULA=TRUE
      # 禁用版本检查以减少网络请求和日志噪音
      - FORGE_FORCE_ANSI=false
      # 禁用网络相关功能以避免卡住
      - VERSION_CHECK=false
      - DISABLE_SENTRY=true
      - DISABLE_BETA_FEATURES=true
      # 网络超时设置
      - HTTP_TIMEOUT=5000
      # 优化 JVM 参数
      - JAVA_OPTS=-XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Dfml.readTimeout=90 -Dfml.loginTimeout=10
    
    ports:
      - "25564:25565"  # Minecraft 服务器端口
    
    volumes:
      # 挂载世界存档和配置文件到主机，实现数据持久化
      - ./data/world:/app/world
      - ./data/modified_data:/app/modified_data
    
    restart: unless-stopped
    
    # 设置内存限制
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 2G
